---  
- hosts: R1
  gather_facts: false
  connection: network_cli
  #ansible_become: yes
  #ansible_become_method: enable
  tasks:
   - name: 'enable'
     eos_command:
       commands: enable 
   
   - name: 'get vlan'
     eos_command:
       commands: show vlan
      
         
   
